### ISSUE TITLE
Implement React Router

### ISSUE THREAD

**Issue by walsquared** [cuhacking/main-website#2]
Before we split off into our own tasks, we need to establish the apps infrastructure. Add [React Router](https://reacttraining.com/react-router/) to the project and create a `pages` directory under `src`. In here we should have `Home.tsx`, `Events.tsx`, and `Blog.tsx` which correspond to the pages specified in the design. 

When finished, you should be able to navigate to `/events` for the event page and `/blog` for the blog (`/` for the home page, of course).

**Comment by Walsker** [comment]
Test comment

**Comment by Walsker** [comment]
Test comment 2
