### ISSUE TITLE
Create common navigation bar and footer components

### ISSUE THREAD

**Issue by walsquared** [cuhacking/main-website#3]
As per the title, In `src/components`, create common components for the whole app. The footer is supposed to mimic the one we currently have [on the current website](https://cuhacking.com/#footer_container__3t0w3), with a couple differences:

- It's black (#000000)
- Instead of "Made with ♥..." it says "Black Lives Matter. [Support the movement.](https://blacklivesmatters.carrd.co/)" and points to this link: https://blacklivesmatters.carrd.co/
- The social icons in the middle column are now at the bottom

To list a few. The short description will be changed soon, but it hasn't been decided what that will be yet. Once it's final, be sure to use it as the meta description in `public/index.html`, like so: `<meta name="description" content="..." />`.

Be sure to follow the design, and use your intuition if any design elements are unspecified/unclear.

**Comment by MrNickCasey** [comment]
Here's the shortlist of components that we'll need: 
- The General Purpose Purple Button. (GPPB)
- Social Links 
- Navbar , Navbar Links 
- Footer, Footer Nav Links,

**Comment by walsquared** [comment]
Completed in #11.
